(()=>{'use strict';
const D=window.MENU_DATA||{prodotti:[],extra:[]},P=D.prodotti,E=D.extra,$=s=>document.querySelector(s),eur=c=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(c/100),cents=n=>Math.round(Number(n)*100),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('it'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}},set=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const storedCart=get('rs-demo-cart-v2',[]),storedFavs=get('rs-demo-favs-v2',[]);
let cart=Array.isArray(storedCart)?storedCart.filter(x=>x&&Number.isInteger(x.pid)&&P[x.pid]&&!P[x.pid].esaurito&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=99&&Array.isArray(x.extras)&&x.extras.every(i=>Number.isInteger(i)&&E[i])&&(!x.extras.length||P[x.pid].supplementi_disponibili)).map(x=>({pid:x.pid,qty:x.qty,extras:[...new Set(x.extras)].sort((a,b)=>a-b)})):[];
let favs=new Set(Array.isArray(storedFavs)?storedFavs.filter(i=>Number.isInteger(i)&&P[i]):[]),cat='Tutto',query='',hideSold=false,onlyFavs=false,current=null,qty=1,lastFocus=null;
const cats=[...new Set(P.map(p=>p.categoria.trim()))];
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.classList.remove('show'),3200)}
function persist(){const ok=set('rs-demo-cart-v2',cart);updateBadge();return ok}
function updateBadge(){$('#cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0)}
function renderCats(){$('#cats').innerHTML=['Tutto',...cats].map(c=>`<button type="button" class="${c===cat?'active':''}" data-cat="${esc(c)}" aria-pressed="${c===cat}">${esc(c)}</button>`).join('')}
function render(){const list=P.map((p,id)=>({...p,id})).filter(p=>(cat==='Tutto'||p.categoria.trim()===cat)&&(!hideSold||!p.esaurito)&&(!onlyFavs||favs.has(p.id))&&(!query||norm(p.nome+' '+p.descrizione).includes(query)));
 $('#resultCount').textContent=`${list.length} ${list.length===1?'voce':'voci'} su ${P.length}`;
 $('#favorites').setAttribute('aria-pressed',String(onlyFavs));$('#favorites').textContent=`♡ Preferiti (${favs.size})`;
 const groups=cats.map(c=>[c,list.filter(p=>p.categoria.trim()===c)]).filter(x=>x[1].length);
 $('#results').innerHTML=groups.length?groups.map(([c,a])=>`<section class="category"><div class="categoryHead"><h2>${esc(c)}</h2><span>${a.length} ${a.length===1?'voce':'voci'}</span></div><div class="grid">${a.map(card).join('')}</div></section>`).join(''):`<div class="emptyState"><h2>${onlyFavs?'Nessun preferito da mostrare':'Nessun risultato'}</h2><p>${onlyFavs?'Salva un piatto con il cuore o modifica i filtri.':'Prova un altro termine o modifica i filtri.'}</p><button class="filterButton" data-reset>Mostra tutto</button></div>`;
}
function card(p){return `<article class="card ${p.esaurito?'esaurito':''}"><button class="fav ${favs.has(p.id)?'on':''}" data-fav="${p.id}" type="button" aria-label="${favs.has(p.id)?'Rimuovi dai':'Aggiungi ai'} preferiti: ${esc(p.nome)}" aria-pressed="${favs.has(p.id)}">${favs.has(p.id)?'♥':'♡'}</button><h3>${esc(p.nome)}</h3>${p.descrizione?`<p class="desc">${esc(p.descrizione)}</p>`:''}<div class="cardBottom"><span class="price">${eur(cents(p.prezzo_eur))}</span>${p.esaurito?'<span class="sold">Esaurito nella rilevazione</span>':`<button class="choose" data-product="${p.id}" aria-label="Personalizza ${esc(p.nome)}">Scegli <span aria-hidden="true">＋</span></button>`}</div></article>`}
function reset(){cat='Tutto';query='';hideSold=false;onlyFavs=false;$('#search').value='';$('#hideSold').checked=false;renderCats();render()}
$('#cats').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;cat=b.dataset.cat;renderCats();render();[...$('#cats').children].find(x=>x.dataset.cat===cat)?.focus({preventScroll:true})});
$('#results').addEventListener('click',e=>{const f=e.target.closest('[data-fav]'),p=e.target.closest('[data-product]');if(f){const id=+f.dataset.fav;favs.has(id)?favs.delete(id):favs.add(id);if(!set('rs-demo-favs-v2',[...favs]))toast('Preferiti conservati solo in questa sessione');render();$(`[data-fav="${id}"]`)?.focus({preventScroll:true})}else if(p)openProduct(+p.dataset.product);else if(e.target.closest('[data-reset]'))reset()});
function openDialog(d){lastFocus=document.activeElement;d.showModal();document.body.classList.add('modal-open')}
for(const d of document.querySelectorAll('dialog')){d.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocus?.focus({preventScroll:true})});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})}
function openProduct(id){if(!P[id]||P[id].esaurito)return;current={pid:id,extras:[]};qty=1;const p=P[id];$('#pCat').textContent=p.categoria.trim();$('#pName').textContent=p.nome;$('#pDesc').textContent=p.descrizione||'Nessuna descrizione pubblicata.';$('#extrasBox').hidden=!p.supplementi_disponibili;$('#extras').innerHTML=p.supplementi_disponibili?E.map((x,i)=>`<label class="extra"><input type="checkbox" value="${i}"><span>${esc(x.nome)}</span><span>+ ${eur(cents(x.prezzo_eur))}</span></label>`).join(''):'';$('#qty').textContent=qty;calcProduct();openDialog($('#productDialog'))}
function calcProduct(){if(!current)return;current.extras=[...$('#extras').querySelectorAll('input:checked')].map(x=>+x.value);$('#pTotal').textContent=eur(lineUnit(current)*qty);$('#qMinus').disabled=qty===1;$('#qPlus').disabled=qty===99}
$('#extras').addEventListener('change',calcProduct);
$('#qMinus').onclick=()=>{qty=Math.max(1,qty-1);$('#qty').textContent=qty;calcProduct()};$('#qPlus').onclick=()=>{qty=Math.min(99,qty+1);$('#qty').textContent=qty;calcProduct()};
$('#addCart').onclick=()=>{calcProduct();const same=cart.find(x=>x.pid===current.pid&&JSON.stringify(x.extras)===JSON.stringify(current.extras));if(same&&same.qty+qty>99){toast('Massimo 99 pezzi per configurazione. Modifica il carrello.');return}same?same.qty+=qty:cart.push({...current,qty});const ok=persist();$('#productDialog').close();toast(ok?'Aggiunto al carrello demo':'Aggiunto. Il carrello resta solo in questa sessione.')};
function lineUnit(x){return cents(P[x.pid].prezzo_eur)+x.extras.reduce((n,i)=>n+cents(E[i].prezzo_eur),0)}
const subtotal=()=>cart.reduce((n,x)=>n+lineUnit(x)*x.qty,0);
function renderCart(){$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>{const p=P[x.pid],extras=x.extras.map(j=>E[j].nome);return `<div class="cartRow"><div><strong>${esc(p.nome)}</strong>${extras.length?`<p>Supplementi: ${esc(extras.join(', '))}</p>`:''}<p>${eur(lineUnit(x))} al pezzo</p></div><div class="miniQty"><button data-act="minus" data-i="${i}" aria-label="Diminuisci ${esc(p.nome)}">−</button><span aria-label="Quantità">${x.qty}</span><button data-act="plus" data-i="${i}" ${x.qty>=99?'disabled':''} aria-label="Aumenta ${esc(p.nome)}">+</button><button class="remove" data-act="remove" data-i="${i}" aria-label="Rimuovi ${esc(p.nome)}">Rimuovi</button></div><span class="lineTotal">${eur(lineUnit(x)*x.qty)}</span></div>`}).join(''):'<div class="emptyState"><strong>Il carrello è vuoto.</strong><p>Aggiungi dal menu i piatti per il tuo riepilogo.</p></div>';
 $('#subtotal').textContent=eur(subtotal());for(const id of ['copy','download','empty'])$('#'+id).disabled=!cart.length;
}
$('#cartItems').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;const i=+b.dataset.i,action=b.dataset.act;if(action==='plus')cart[i].qty=Math.min(99,cart[i].qty+1);if(action==='minus'){cart[i].qty--;if(cart[i].qty===0)cart.splice(i,1)}if(action==='remove')cart.splice(i,1);if(!persist())toast('Modifica salvata solo in questa sessione');renderCart();$(`[data-act="${action}"][data-i="${i}"]`)?.focus({preventScroll:true})});
let preference=get('rs-demo-preference','');if(!['Ritiro','Consegna'].includes(preference))preference='';document.querySelectorAll('[name=fulfil]').forEach(r=>{r.checked=r.value===preference;r.addEventListener('change',()=>{preference=r.value;set('rs-demo-preference',preference)})});
function recap(){const lines=['REGINA SOFIA — RIEPILOGO DEMO','Anteprima: nessun ordine inviato','Dati menu: 05/10/2026','Preferenza (solo indicativa): '+(preference||'non indicata'),''];cart.forEach(x=>lines.push(`${x.qty} × ${P[x.pid].nome} — ${eur(lineUnit(x)*x.qty)}${x.extras.length?' | Supplementi: '+x.extras.map(i=>E[i].nome).join(', '):''}`));lines.push('',`Subtotale (consegna e altri eventuali costi esclusi): ${eur(subtotal())}`,'Disponibilità e supplementi da confermare sul servizio ufficiale.','Il carrello demo non viene trasferito automaticamente.','https://delivery.reginasofia.it/');return lines.join('\n')}
$('#openCart').onclick=()=>{renderCart();openDialog($('#cartDialog'))};$('#closeCart').onclick=()=>$('#cartDialog').close();$('#empty').onclick=()=>{cart=[];persist();renderCart();toast('Carrello svuotato')};
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(recap());toast('Riepilogo copiato')}catch{const box=$('#copyFallback');box.hidden=false;box.value=recap();box.focus();box.select();toast('Tieni premuto sul testo per copiarlo.')}};
$('#download').onclick=()=>{const a=document.createElement('a'),blob=new Blob([recap()],{type:'text/plain;charset=utf-8'});a.href=URL.createObjectURL(blob);a.download='riepilogo-regina-sofia-demo.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#search').oninput=e=>{query=norm(e.target.value.trim());cat='Tutto';renderCats();render()};$('#hideSold').onchange=e=>{hideSold=e.target.checked;render()};$('#favorites').onclick=()=>{onlyFavs=!onlyFavs;cat='Tutto';query='';$('#search').value='';renderCats();render()};$('#resetFilters').onclick=reset;
if(location.protocol==='file:'){$('#download').hidden=true;$('#reportLink').hidden=true;$('#offlineNote').textContent='Catalogo incluso nell’app e consultabile offline. Il servizio ordini ufficiale richiede Internet e si apre nel browser.'}else if('serviceWorker' in navigator)navigator.serviceWorker.register('../sw.js').catch(()=>{});
renderCats();render();updateBadge();
})();
